version: '3.8'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True
    ports:
      - "8000:8000"

  celery_worker:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True

  celery_beat:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=True
