# Generated by Django 4.2.30 on 2026-07-12 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("service_name", models.CharField(db_index=True, max_length=100)),
                (
                    "severity",
                    models.CharField(db_index=True, default="INFO", max_length=20),
                ),
                ("message", models.TextField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Log Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
