# Generated by Django 4.2.30 on 2026-07-12 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("is_anomaly", models.BooleanField(default=True)),
                ("model_version", models.CharField(db_index=True, max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "log_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly",
                        to="logs.logentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anomalies",
                "ordering": ["-created_at"],
            },
        ),
    ]
